lastVersion: 1.0
debug: false
metricsEnabled: true
defaultLanguage: en-gb
commandCooldownSeconds: 5
database:
  type: sqlite
  name: commandsex
  host: localhost
  port: 3306
  username: root
  password: ""
  prefix: cex_